// Hallmark 的 21 个主题一共用到 18 个字体家族。
// 静态家族只引 latin 分片；可变家族引 index.css，浏览器仍只会下载命中的那个分片。
import '@fontsource-variable/fraunces/index.css'
import '@fontsource-variable/geist/index.css'
import '@fontsource-variable/archivo/index.css'
import '@fontsource-variable/albert-sans/index.css'
import '@fontsource-variable/hanken-grotesk/index.css'
import '@fontsource-variable/newsreader/index.css'
import '@fontsource-variable/jetbrains-mono/index.css'
import '@fontsource-variable/public-sans/index.css'
import '@fontsource-variable/inter-tight/index.css'
import '@fontsource-variable/space-grotesk/index.css'
import '@fontsource-variable/dm-sans/index.css'
import '@fontsource-variable/plus-jakarta-sans/index.css'

import '@fontsource/playfair-display/latin-400.css'
import '@fontsource/playfair-display/latin-700.css'
import '@fontsource/playfair-display/latin-900.css'
import '@fontsource/big-shoulders-display/latin-700'
import '@fontsource/anton/latin-400.css'
import '@fontsource/young-serif/latin-400.css'
import '@fontsource/instrument-serif/latin-400.css'
import '@fontsource/geist-mono/latin-400.css'
import '@fontsource/geist-mono/latin-500.css'
import '@fontsource/ibm-plex-mono/latin-400.css'
import '@fontsource/ibm-plex-mono/latin-500.css'
